services:
  docker-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=production
    restart: unless-stopped