version: "3.8"
services:
  containly:
    build: .
    image: cloudsmithy/containly
    container_name: containly
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=5001
      - FLASK_DEBUG=false
      - REFRESH_INTERVAL=30
      - LOG_LINES=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
